document.addEventListener('DOMContentLoaded', () => {
    const dropdownButton = document.getElementById('dropdownButton');
    const dropdownList = document.getElementById('yearDropdown');
    const teamTitle = document.getElementById('teamTitle');
    const teamsList = document.getElementById('teamsList');
    const teamLogoElement = document.getElementById('teamLogo');
    const teamNameElement = document.getElementById('teamName');
    const playerGrid = document.getElementById('playerGrid');
    const playersSection = document.querySelector('.players-section');

    const teams = {
        2025: [
            { name: "HLE", logo: "/photos/assets/HLE.svg", players: [{ name: "Zeus", image: "/photos/players/Zeus.jpg", position: "TOP", nameKr: "최우제"  }, { name: "Peanut", image: "/photos/players/Peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Zeka", image: "/photos/players/Zeka.jpg", position: "MID", nameKr: "김건우"  }, { name: "Viper", image: "/photos/players/Viper.jpg", position: "BOT", nameKr: "박도현"  },{ name: "Delight", image: "/photos/players/Delight.jpg", position: "SUP", nameKr: "유환중"  }] },
            { name: "GEN.G", logo: "/photos/assets/GEN.G.svg", players: [{name: "Kiin", image: "/photos/players/Kiin.jpg", position: "TOP", nameKr: "김기인" }, { name: "Canyon", image: "/photos/players/Canyon.jpg", position: "JUG", nameKr: "김건부" }, { name: "Chovy", image: "/photos/players/chovy.jpg", position: "MID", nameKr: "정지훈" }, { name: "Ruler", image: "/photos/players/Ruler.jpg", position: "BOT", nameKr: "박재혁" }, { name: "Duro", image: "/photos/players/Duro.jpg", position: "SUP", nameKr: "주민규" }] },
            { name: "T1", logo: "/photos/assets/T1.svg", players: [{ name: "Doran", image: "/photos/players/Doran.jpg", position: "TOP", nameKr: "최현준" }, { name: "Oner", image: "/photos/players/Oner.jpg", position: "JUG", nameKr: "문현준" },  { name: "Faker", image: "/photos/players/Faker.jpg", position: "MID", nameKr: "이상혁"  },   { name: "Smash", image: "/photos/players/Smash.jpg" , position: "BOT", nameKr: "신금재" },  { name: "Keria", image: "/photos/players/Keria.jpg", position: "SUP", nameKr: "류민석"  }]},
            { name: "Dplus KIA", logo: "/photos/assets/DK.svg", players: [{ name: "Siwoo", image: "/photos/players/Siwoo.jpg",position: "TOP", nameKr: "전시우" }, { name: "Lucid", image: "/photos/players/Lucid.jpg",position: "JUG", nameKr: "최용혁" }, { name: "ShowMaker", image: "/photos/players/ShowMaker.jpg",position: "MID", nameKr: "허수" }, { name: "Aiming", image: "/photos/players/Aiming.jpg",position: "BOT", nameKr: "김하람" }, { name: "BeryL", image: "/photos/players/BeryL.jpg",position: "SUP", nameKr: "조건희" }] },
            { name: "KT", logo: "/photos/assets/KT.svg", players: [{ name: "PerfecT", image: "/photos/players/PerfecT.jpg", position: "TOP", nameKr: "이승민" }, { name: "Cuzz", image: "/photos/players/Cuzz.jpg", position: "JUG", nameKr: "문우찬" }, { name: "Bdd", image: "/photos/players/Bdd.jpg", position: "MID", nameKr: "곽보성" }, { name: "Deokdam", image: "/photos/players/deokdam.jpg", position: "BOT", nameKr: "서대길" }, { name: "Way", image: "/photos/players/Way.jpg", position: "SUP", nameKr: "한길" }] },
            { name: "BNK", logo: "/photos/assets/BNK.png", players: [{ name: "Clear", image: "/photos/players/Clear.jpg", position: "TOP", nameKr: "송현민" }, { name: "Raptor", image: "/photos/players/Raptor.jpg", position: "JUG", nameKr: "전어진" }, { name: "VicLa", image: "/photos/players/VicLa.jpg", position: "MID", nameKr: "이대광" }, { name: "Diable", image: "/photos/players/Diable.jpg", position: "BOT", nameKr: "남대근" }, { name: "Kellin", image: "/photos/players/Kellin.jpg", position: "SUP", nameKr: "김형규" }] },
            { name: "DNF", logo: "/photos/assets/DNF.svg", players: [{ name: "DuDu", image: "/photos/players/DuDu.jpg", position: "TOP", nameKr: "이동주" }, { name: "Pyosik", image: "/photos/players/Pyosik.jpg", position: "JUG", nameKr: "홍창현" }, { name: "BuLLDoG", image: "/photos/players/BuLLDog.jpg", position: "MID", nameKr: "이태영" }, { name: "Berserker", image: "/photos/players/Berserker.jpg", position: "BOT", nameKr: "김민철" }, { name: "Life", image: "/photos/players/Life.jpg", position: "SUP", nameKr: "김정민" }] },
            { name: "NS", logo: "/photos/assets/NS.svg", players: [{ name: "Kingen", image: "/photos/players/Kingen.jpg", position: "TOP", nameKr: "황성훈" }, { name: "GIDEON", image: "/photos/players/GIDEON.jpg", position: "JUG", nameKr: "김민성" }, { name: "Fisher", image: "/photos/players/Fisher.jpg", position: "MID", nameKr: "이정태" }, { name: "Jiwoo", image: "/photos/players/Jiwoo.jpg", position: "BOT", nameKr: "정지우" }, { name: "Lehends", image: "/photos/players/Lehends.jpg", position: "SUP", nameKr: "손시우" }] },
            { name: "DRX", logo: "/photos/assets/DRX.svg", players: [{ name: "Rich", image: "/photos/players/Rich.jpg", position: "TOP", nameKr: "이재원" }, { name: "Sponge", image: "/photos/players/Sponge.jpg", position: "JUG", nameKr: "배영준" }, { name: "Ucal", image: "/photos/players/Ucal.jpg", position: "MID", nameKr: "손우현" }, { name: "teddy", image: "/photos/players/Teddy.jpg", position: "BOT", nameKr: "박진성" }, { name: "Andil", image: "/photos/players/Andil.jpg", position: "SUP", nameKr: "문관빈" }] },
            { name: "BRION", logo: "/photos/assets/BRO.svg", players: [{ name: "Morgan", image: "/photos/players/Morgan.jpg", position: "TOP", nameKr: "박루한" }, { name: "HamBak", image: "/photos/players/HamBak.jpg", position: "JUG", nameKr: "함유진" }, { name: "Clozer", image: "/photos/players/Clozer.jpg", position: "MID", nameKr: "이주현" }, { name: "Hype", image: "/photos/players/Hype.jpg", position: "BOT", nameKr: "변정현" }, { name: "Pollu", image: "/photos/players/Pollu.jpg", position: "SUP", nameKr: "오동규" }] },
        ],
        2024: [
            { name: "GEN.G", logo: "/photos/assets/GEN.G.svg", players: [{  name: "Kiin", image: "/photos/players/Kiin.jpg", position: "TOP", nameKr: "김기인"  }, { name: "Canyon", image: "/photos/players/Canyon.jpg" , position: "JUG", nameKr: "김건부" }, { name: "Chovy", image: "/photos/players/chovy.jpg", position: "MID", nameKr: "정지훈"  }, { name: "Peyz", image: "/photos/players/peyz.jpg", position: "BOT", nameKr: "김수환"  },{ name: "Lehends", image: "/photos/players/Lehends.jpg", position: "SUP", nameKr: "손시우"  }] },
            { name: "T1", logo: "/photos/assets/T1.svg", players: [{  name: "Zeus", image: "/photos/players/Zeus.jpg", position: "TOP", nameKr: "최우제"  }, { name: "Oner", image: "/photos/players/Oner.jpg" , position: "JUG", nameKr: "문현준" }, { name: "Faker", image: "/photos/players/Faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Gumayusi", image: "/photos/players/Gumayusi.jpg", position: "BOT", nameKr: "이민형"  },{ name: "Keria", image: "/photos/players/Keria.jpg", position: "SUP", nameKr: "류민석"  }] },
            { name: "HLE", logo: "/photos/assets/HLE.svg", players: [{ name: "Doran", image: "/photos/players/Doran.jpg", position: "TOP", nameKr: "최현준"  }, { name: "Peanut", image: "/photos/players/Peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Zeka", image: "/photos/players/Zeka.jpg", position: "MID", nameKr: "김건우"  }, { name: "Viper", image: "/photos/players/Viper.jpg", position: "BOT", nameKr: "박도현"  },{ name: "Delight", image: "/photos/players/Delight.jpg", position: "SUP", nameKr: "유환중"  }] },
            { name: "KT", logo: "/photos/assets/KT.svg", players: [{  name: "PerfecT", image: "/photos/players/PerfecT.jpg", position: "TOP", nameKr: "이승민"  }, { name: "Pyosik", image: "/photos/players/Pyosik.jpg" , position: "JUG", nameKr: "홍창현" }, { name: "Bdd", image: "/photos/players/Bdd.jpg", position: "MID", nameKr: "곽보성"  }, { name: "Deft", image: "/photos/players/Deft.jpg", position: "BOT", nameKr: "김혁규"  },{ name: "BeryL", image: "/photos/players/BeryL.jpg", position: "SUP", nameKr: "조건희"  }] },
            { name: "Dplus KIA", logo: "/photos/assets/DK.svg", players: [{ name: "Kingen", image: "/photos/players/Kingen.jpg", position: "TOP", nameKr: "황성훈"  }, { name: "Lucid", image: "/photos/players/Lucid.jpg" , position: "JUG", nameKr: "최용혁" }, { name: "ShowMaker", image: "/photos/players/ShowMaker.jpg", position: "MID", nameKr: "허수"  }, { name: "Aiming", image: "/photos/players/Aiming.jpg", position: "BOT", nameKr: "김하람"  },{ name: "Keliin", image: "/photos/players/Kellin.jpg", position: "SUP", nameKr: "김형규"  }] },
            { name: "KDF", logo: "/photos/assets/KDF.svg", players: [{ name: "DuDu", image: "/photos/players/DuDu.jpg", position: "TOP", nameKr: "이동주"  }, { name: "Cuzz", image: "/photos/players/Cuzz.jpg" , position: "JUG", nameKr: "문우찬" }, { name: "BullDog", image: "/photos/players/BuLLDog.jpg", position: "MID", nameKr: "이태영"  }, { name: "Bull", image: "/photos/players/Bull.jpg", position: "BOT", nameKr: "송선규"  },{ name: "quantam", image: "/photos/players/Quantum.jpg", position: "SUP", nameKr: "손정환"  }] },
            { name: "FOX", logo: "/photos/assets/2024 BNK.svg", players: [{  name: "Clear", image: "/photos/players/Clear.jpg", position: "TOP", nameKr: "송현민"  }, { name: "Willer", image: "/photos/players/Willer.jpg" , position: "JUG", nameKr: "김정현" }, { name: "Clozer", image: "/photos/players/Clozer.jpg", position: "MID", nameKr: "이주현"  }, { name: "Hena", image: "/photos/players/hena.jpg", position: "BOT", nameKr: "박증환"  },{ name: "Execute", image: "/photos/players/execute.jpg", position: "SUP", nameKr: "이정훈"  }] },
            { name: "NS", logo: "/photos/assets/NS.svg", players: [{  name: "DnDn", image: "/photos/players/dndn.jpg", position: "TOP", nameKr: "박근우"  }, { name: "Sylvie", image: "/photos/players/Sylvie.jpg" , position: "JUG", nameKr: "이승복" }, { name: "Callme", image: "/photos/players/callme.jpg", position: "MID", nameKr: "오지훈"  }, { name: "jiwoo", image: "/photos/players/Jiwoo.jpg", position: "BOT", nameKr: "정지우" },{ name: "Peter", image: "/photos/players/Peter.jpg", position: "SUP", nameKr: "정윤수"  }] },
            { name: "DRX", logo: "/photos/assets/DRX.svg", players: [{  name: "Rascal", image: "/photos/players/Rascal.jpg", position: "TOP", nameKr: "김광희"  }, { name: "Sponge", image: "/photos/players/Sponge.jpg" , position: "JUG", nameKr: "배영준" }, { name: "Kyeahoo", image: "/photos/players/Kyeahoo.jpg", position: "MID", nameKr: "강예후"  }, { name: "Teddy", image: "/photos/players/Teddy.jpg", position: "BOT", nameKr: "박진성"  },{ name: "Pleata", image: "/photos/players/Pleata.jpg", position: "SUP", nameKr: "손민우"  }] },
            { name: "BRION", logo: "/photos/assets/BRO.svg", players: [{ name: "Morgan", image: "/photos/players/Morgan.jpg", position: "TOP", nameKr: "박루한"  }, { name: "GIDEON", image: "/photos/players/GIDEON.jpg" , position: "JUG", nameKr: "김민성" }, { name: "Karis", image: "/photos/players/karis.jpg", position: "MID", nameKr: "김홍조"  }, { name: "Envy", image: "/photos/players/envy.jpg", position: "BOT", nameKr: "이명준"  },{ name: "Pollu", image: "/photos/players/Pollu.jpg", position: "SUP", nameKr: "오동규"  }] },
        ],
        2023: [
            { name: "T1", logo: "/photos/assets/T1.svg", players: [{  name: "Zeus", image: "/photos/players/Zeus.jpg", position: "TOP", nameKr: "최우제"  }, { name: "Oner", image: "/photos/players/Oner.jpg" , position: "JUG", nameKr: "문현준" }, { name: "Faker", image: "/photos/players/Faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Gumayusi", image: "/photos/players/Gumayusi.jpg", position: "BOT", nameKr: "이민형"  },{ name: "Keria", image: "/photos/players/Keria.jpg", position: "SUP", nameKr: "류민석"  }] },
            { name: "GEN.G", logo: "/photos/assets/GEN.G.svg", players: [{  name: "Doran", image: "/photos/players/Doran.jpg", position: "TOP", nameKr: "최현준"  }, { name: "Peanut", image: "/photos/players/Peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Chovy", image: "/photos/players/chovy.jpg", position: "MID", nameKr: "정지훈"  }, { name: "Peyz", image: "/photos/players/peyz.jpg", position: "BOT", nameKr: "김수환"  },{ name: "Delight", image: "/photos/players/Delight.jpg", position: "SUP", nameKr: "유환중"  }] },
            { name: "KT", logo: "/photos/assets/KT.svg", players: [{ name: "Kiin", image: "/photos/players/Kiin.jpg", position: "TOP", nameKr: "김기인"  }, { name: "Cuzz", image: "/photos/players/Cuzz.jpg" , position: "JUG", nameKr: "문우찬" }, { name: "Bdd", image: "/photos/players/Bdd.jpg", position: "MID", nameKr: "곽보성"  }, { name: "Aiming", image: "/photos/players/Aiming.jpg", position: "BOT", nameKr: "김하람"  },{ name: "Lehends", image: "/photos/players/Lehends.jpg", position: "SUP", nameKr: "손시우"  }] },
            { name: "Dplus KIA", logo: "/photos/assets/DK.svg", players: [{  name: "Canna", image: "/photos/players/canna.jpg", position: "TOP", nameKr: "김창동"  }, { name: "Canyon", image: "/photos/players/Canyon.jpg" , position: "JUG", nameKr: "김건부" }, { name: "ShowMaker", image: "/photos/players/ShowMaker.jpg", position: "MID", nameKr: "허수"  }, { name: "Deft", image: "/photos/players/Deft.jpg", position: "BOT", nameKr: "김혁규"  },{ name: "Kellin", image: "/photos/players/Kellin.jpg", position: "SUP", nameKr: "김형규"  }] },
            { name: "HLE", logo: "/photos/assets/HLE.svg", players: [{  name: "Kingen", image: "/photos/players/Kingen.jpg", position: "TOP", nameKr: "황성훈"  }, { name: "Clid", image: "/photos/players/clid.jpg" , position: "JUG", nameKr: "김태민" }, { name: "Zeka", image: "/photos/players/Zeka.jpg", position: "MID", nameKr: "김건우"  }, { name: "Viper", image: "/photos/players/Viper.jpg", position: "BOT", nameKr: "박도현"  },{ name: "Life", image: "/photos/players/Life.jpg", position: "SUP", nameKr: "김정민"  }] },
            { name: "LSB", logo: "/photos/assets/2023 BNK.svg", players: [{  name: "Burdol", image: "/photos/players/burdol.jpg", position: "TOP", nameKr: "노태윤"  }, { name: "Willer", image: "/photos/players/Willer.jpg" , position: "JUG", nameKr: "김정현" }, { name: "Clozer", image: "/photos/players/Clozer.jpg", position: "MID", nameKr: "이주현"  }, { name: "Envy", image: "/photos/players/envy.jpg", position: "BOT", nameKr: "이명준"  },{ name: "Kael", image: "/photos/players/kael.jpg", position: "SUP", nameKr: "김진홍"  }] },
            { name: "KDF", logo: "/photos/assets/KDF.svg", players: [{  name: "dudu", image: "/photos/players/DuDu.jpg", position: "TOP", nameKr: "이동주"  }, { name: "YoungJae", image: "/photos/players/youngjae.jpg" , position: "JUG", nameKr: "고영재" }, { name: "Bulldog", image: "/photos/players/BuLLDog.jpg", position: "MID", nameKr: "이태영"  }, { name: "Taeyoon", image: "/photos/players/taeyoon.jpg", position: "BOT", nameKr: "김태윤"  },{ name: "JUN", image: "/photos/players/jun.jpg", position: "SUP", nameKr: "윤세준"  }] },
            { name: "BRO", logo: "/photos/assets/2023 BRO.svg", players: [{  name: "Morgan", image: "/photos/players/Morgan.jpg", position: "TOP", nameKr: "박루한"  }, { name: "Umti", image: "/photos/players/umti.jpg" , position: "JUG", nameKr: "엄성현" }, { name: "Karis", image: "/photos/players/karis.jpg", position: "MID", nameKr: "김홍조"  }, { name: "Hena", image: "/photos/players/hena.jpg", position: "BOT", nameKr: "박증환"  },{ name: "Effort", image: "/photos/players/Effort.jpg", position: "SUP", nameKr: "이상호"  }] },
            { name: "DRX", logo: "/photos/assets/DRX.svg", players: [{  name: "Rascal", image: "/photos/players/Rascal.jpg", position: "TOP", nameKr: "김광희"  }, { name: "Croco", image: "/photos/players/Croco.jpg" , position: "JUG", nameKr: "김동범" }, { name: "Fate", image: "/photos/players/fate.jpg", position: "MID", nameKr: "유수혁"  }, { name: "Deokdam", image: "/photos/players/deokdam.jpg", position: "BOT", nameKr: "서대길"  },{ name: "BeryL", image: "/photos/players/BeryL.jpg", position: "SUP", nameKr: "조건희"  }] },
            { name: "NS", logo: "/photos/assets/NS.svg", players: [{  name: "DnDn", image: "/photos/players/dndn.jpg", position: "TOP", nameKr: "박근우"  }, { name: "Sylvie", image: "/photos/players/Sylvie.jpg" , position: "JUG", nameKr: "이승복" }, { name: "Fiesta", image: "/photos/players/fiesta.jpg", position: "MID", nameKr: "안현서"  }, { name: "Vital", image: "/photos/players/Vital.jpg", position: "BOT", nameKr: "하인성"  },{ name: "peter", image: "/photos/players/Peter.jpg", position: "SUP", nameKr: "정윤수"  }] },
        ],
        2022: [
            { name: "T1", logo: "/photos/assets/T1.svg", players: [{ name: "Zeus", image: "/photos/players/Zeus.jpg", position: "TOP", nameKr: "최우제"  }, { name: "Oner", image: "/photos/players/Oner.jpg" , position: "JUG", nameKr: "문현준" }, { name: "Faker", image: "/photos/players/Faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Gumayusi", image: "/photos/players/Gumayusi.jpg", position: "BOT", nameKr: "이민형"  },{ name: "Keria", image: "/photos/players/Keria.jpg", position: "SUP", nameKr: "류민석"  }] },
            { name: "GEN.G", logo: "/photos/assets/GEN.G.svg", players: [{  name: "Doran", image: "/photos/players/Doran.jpg", position: "TOP", nameKr: "최현준"  }, { name: "Peanut", image: "/photos/players/Peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Chovy", image: "/photos/players/chovy.jpg", position: "MID", nameKr: "정지훈"  }, { name: "Ruler", image: "/photos/players/Ruler.jpg", position: "BOT", nameKr: "박재혁"  },{ name: "Lehends", image: "/photos/players/Lehends.jpg", position: "SUP", nameKr: "손시우"  }] },
            { name: "Dplus KIA", logo: "/photos/assets/2022 DK.svg", players: [{  name: "Burdol", image: "/photos/players/burdol.jpg", position: "TOP", nameKr: "노태윤"  }, { name: "Canyon", image: "/photos/players/Canyon.jpg" , position: "JUG", nameKr: "김건부" }, { name: "ShowMaker", image: "/photos/players/ShowMaker.jpg", position: "MID", nameKr: "허수"  }, { name: "Deokdam", image: "/photos/players/deokdam.jpg", position: "BOT", nameKr: "서대길"  },{ name: "Kellin", image: "/photos/players/Kellin.jpg", position: "SUP", nameKr: "김형규"  }] },
            { name: "DRX", logo: "/photos/assets/DRX.svg", players: [{  name: "Kingen", image: "/photos/players/Kingen.jpg", position: "TOP", nameKr: "황성훈"  }, { name: "Pyosik", image: "/photos/players/Pyosik.jpg" , position: "JUG", nameKr: "홍창현" }, { name: "Zeka", image: "/photos/players/Zeka.jpg", position: "MID", nameKr: "김건우"  }, { name: "Deft", image: "/photos/players/Deft.jpg", position: "BOT", nameKr: "김혁규"  },{ name: "BeryL", image: "/photos/players/BeryL.jpg", position: "SUP", nameKr: "조건희"  }] },
            { name: "KDF", logo: "/photos/assets/KDF.svg", players: [{  name: "Kiin", image: "/photos/players/Kiin.jpg", position: "TOP", nameKr: "김기인"  }, { name: "Elim", image: "/photos/players/elim.jpg" , position: "JUG", nameKr: "최엘림" }, { name: "Fate", image: "/photos/players/fate.jpg", "position": "MID", "nameKr": "유수혁"  }, { "name": "Teddy", "image": "/photos/players/Teddy.jpg", "position": "BOT", "nameKr": "박진성"  },{ "name": "Hoit", "image": "/photos/players/hoit.jpg", "position": "SUP", "nameKr": "류호성"  }] },
            { "name": "BRO", "logo": "/photos/assets/2022 BRO.svg", "players": [{  "name": "morgan", "image": "/photos/players/Morgan.jpg", "position": "TOP", "nameKr": "박루한"  }, { "name": "Umti", "image": "/photos/players/umti.jpg" , "position": "JUG", "nameKr": "엄성현" }, { "name": "Lava", "image": "/photos/players/lava.jpg", "position": "MID", "nameKr": "김태훈"  }, { "name": "Hena", "image": "/photos/players/hena.jpg", "position": "BOT", "nameKr": "박증환"  },{ "name": "Delight", "image": "/photos/players/Delight.jpg", "position": "SUP", "nameKr": "유환중"  }] },
            { "name": "KT", "logo": "/photos/assets/KT.svg", "players": [{  "name": "Rascal", "image": "/photos/players/Rascal.jpg", "position": "TOP", "nameKr": "김광희"  }, { "name": "Cuzz", "image": "/photos/players/Cuzz.jpg" , "position": "JUG", "nameKr": "문우찬" }, { "name": "VicLa", "image": "/photos/players/VicLa.jpg", "position": "MID", "nameKr": "이대광"  }, { "name": "Aiming", "image": "/photos/players/Aiming.jpg", "position": "BOT", "nameKr": "김하람"  },{ "name": "Life", "image": "/photos/players/Life.jpg", "position": "SUP", "nameKr": "김정민"  }] },
            { "name": "NS", "logo": "/photos/assets/NS.svg", "players": [{  "name": "Canna", "image": "/photos/players/canna.jpg", "position": "TOP", "nameKr": "김창동"  }, { "name": "Dread", "image": "/photos/players/dread.jpg" , "position": "JUG", "nameKr": "이진혁" }, { "name": "Bdd", "image": "/photos/players/Bdd.jpg", "position": "MID", "nameKr": "곽보성"  }, { "name": "Ghost", "image": "/photos/players/ghost.jpg", "position": "BOT", "nameKr": "장용준"  },{ "name": "Effort", "image": "/photos/players/Effort.jpg", "position": "SUP", "nameKr": "이상호"  }] },
            { "name": "LSB", "logo": "/photos/assets/2023 BNK.svg", "players": [{  "name": "Dove", "image": "/photos/players/dove.jpg", "position": "TOP", "nameKr": "김재연"  }, { "name": "Croco", "image": "/photos/players/Croco.jpg" , "position": "JUG", "nameKr": "김동범" }, { "name": "Clozer", "image": "/photos/players/Clozer.jpg", "position": "MID", "nameKr": "이주현"  }, { "name": "Ice", "image": "/photos/players/ice.jpg", "position": "BOT", "nameKr": "윤상훈"  },{ "name": "Kael", "image": "/photos/players/kael.jpg", "position": "SUP", "nameKr": "김진홍"  }] },
            { "name": "HLE", "logo": "/photos/assets/HLE.svg", "players": [{  "name": "DuDu", "image": "/photos/players/DuDu.jpg", "position": "TOP", "nameKr": "이동주"  }, { "name": "Onfleek", "image": "/photos/players/onfleek.jpg" , "position": "JUG", "nameKr": "김장겸" }, { "name": "Karis", "image": "/photos/players/karis.jpg", "position": "MID", "nameKr": "김홍조"  }, { "name": "SamD", "image": "/photos/players/samd.jpg", "position": "BOT", "nameKr": "이재훈"  },{ "name": "Vsta", "image": "/photos/players/vsta.jpg", "position": "SUP", "nameKr": "오효성"  }] },
        ],
        2021: [
            { name: "Dplus KIA", logo: "/photos/assets/2022 DK.svg", players: [{  name: "Khan", image: "/photos/players/Khan.jpg", position: "TOP", nameKr: "김동하"  }, { name: "Canyon", image: "/photos/players/Canyon.jpg" , position: "JUG", nameKr: "김건부" }, { name: "ShowMaker", image: "/photos/players/ShowMaker.jpg", position: "MID", nameKr: "허수"  }, { name: "Ghost", image: "/photos/players/ghost.jpg", position: "BOT", nameKr: "장용준"  },{ name: "BeryL", image: "/photos/players/BeryL.jpg", position: "SUP", nameKr: "조건희"  }] },
            { name: "GEN.G", logo: "/photos/assets/GEN.G.svg", players: [{  name: "Rascal", image: "/photos/players/Rascal.jpg", position: "TOP", nameKr: "김광희"  }, { name: "Clid", image: "/photos/players/clid.jpg" , position: "JUG", nameKr: "김태민" }, { name: "Bdd", image: "/photos/players/Bdd.jpg", position: "MID", nameKr: "곽보성"  }, { name: "Ruler", image: "/photos/players/Ruler.jpg", position: "BOT", nameKr: "박재혁"  },{ name: "Life", image: "/photos/players/Life.jpg", position: "SUP", nameKr: "김정민"  }] },
            { name: "HLE", logo: "/photos/assets/HLE.svg", players: [{  name: "Morgan", image: "/photos/players/Morgan.jpg", position: "TOP", nameKr: "박루한"  }, { name: "Arthur", image: "/photos/players/arthur.jpg" , position: "JUG", nameKr: "박미르" }, { name: "Chovy", image: "/photos/players/chovy.jpg", position: "MID", nameKr: "정지훈"  }, { name: "Deft", image: "/photos/players/Deft.jpg", position: "BOT", nameKr: "김혁규"  },{ name: "Vsta", image: "/photos/players/vsta.jpg", position: "SUP", nameKr: "오효성"  }] },
            { name: "T1", logo: "/photos/assets/T1.svg", players: [{  name: "Canna", image: "/photos/players/canna.jpg", position: "TOP", nameKr: "김창동"  }, { name: "CuzZ", image: "/photos/players/Cuzz.jpg" , position: "JUG", nameKr: "문우찬" }, { name: "Faker", image: "/photos/players/Faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Teddy", image: "/photos/players/Teddy.jpg", position: "BOT", nameKr: "박진성"  },{ name: "Keria", image: "/photos/players/Keria.jpg", position: "SUP", nameKr: "류민석"  }] },
            { name: "DRX", logo: "/photos/assets/DRX.svg", players: [{  name: "Kingen", image: "/photos/players/Kingen.jpg", position: "TOP", nameKr: "황성훈"  }, { name: "Pyosik", image: "/photos/players/Pyosik.jpg" , position: "JUG", nameKr: "홍창현" }, { name: "Solka", image: "/photos/players/solka.jpg", position: "MID", nameKr: "송수형"  }, { name: "Bao", image: "/photos/players/bao.jpg", position: "BOT", nameKr: "정현우"  },{ name: "Pleata", image: "/photos/players/Pleata.jpg", position: "SUP", nameKr: "손민우"  }] },
            { name: "NS", logo: "/photos/assets/NS.svg", players: [{  name: "Rich", image: "/photos/players/Rich.jpg", position: "TOP", nameKr: "이재원"  }, { name: "Peanut", image: "/photos/players/Peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Bay", image: "/photos/players/bay.jpg", position: "MID", nameKr: "박준병"  }, { name: "Deokdam", image: "/photos/players/deokdam.jpg", position: "BOT", nameKr: "서대길"  },{ name: "Kellin", image: "/photos/players/Kellin.jpg", position: "SUP", nameKr: "김형규"  }] },
            { name: "KT", logo: "/photos/assets/2021 KT.svg", players: [{  name: "Doran", image: "/photos/players/Doran.jpg", position: "TOP", nameKr: "최현준"  }, { name: "GIDEON", image: "/photos/players/GIDEON.jpg" , position: "JUG", nameKr: "김민성" }, { name: "Dove", image: "/photos/players/dove.jpg", position: "MID", nameKr: "김재연"  }, { name: "Noah", image: "/photos/players/noah.jpg", position: "BOT", nameKr: "오현택"  },{ name: "Zzus", image: "/photos/players/zzus.jpg", position: "SUP", nameKr: "장준수"  }] },
            { name: "LSB", logo: "/photos/assets/2023 BNK.svg", players: [{  name: "Summit", image: "/photos/players/summit.jpg", position: "TOP", nameKr: "박우태"  }, { name: "Croco", image: "/photos/players/Croco.jpg" , position: "JUG", nameKr: "김동범" }, { name: "Fate", image: "/photos/players/fate.jpg", position: "MID", nameKr: "유수혁"  }, { name: "Route", image: "/photos/players/route.jpg", position: "BOT", nameKr: "문검수"  },{ name: "Effort", image: "/photos/players/Effort.jpg", position: "SUP", nameKr: "이상호"  }] },
            { name: "AF", logo: "/photos/assets/AF.png", players: [{  name: "Kiin", image: "/photos/players/Kiin.jpg", position: "TOP", nameKr: "김기인"  }, { name: "Dread", image: "/photos/players/dread.jpg" , position: "JUG", nameKr: "이진혁" }, { name: "Fly", image: "/photos/players/fly.jpg", position: "MID", nameKr: "송용준"  }, { name: "Bang", image: "/photos/players/bang.jpg", position: "BOT", nameKr: "배준식"  },{ name: "Lehends", image: "/photos/players/Lehends.jpg", position: "SUP", nameKr: "손시우"  }] },
            { name: "BRO", logo: "/photos/assets/2022 BRO.svg", players: [{  name: "Hoya", image: "/photos/players/hoya.jpg", position: "TOP", nameKr: "윤용호"  }, { name: "Umti", image: "/photos/players/umti.jpg" , position: "JUG", nameKr: "엄성현" }, { name: "Lava", image: "/photos/players/lava.jpg", position: "MID", nameKr: "김태훈"  }, { name: "Hena", image: "/photos/players/hena.jpg", position: "BOT", nameKr: "박증환"  },{ name: "Delight", image: "/photos/players/Delight.jpg", position: "SUP", nameKr: "유환중"  }] },
        ],
        2020: [
            { name: "GEN.G", logo: "/photos/assets/GEN.G.svg", players: [{  name: "Rascal", image: "/photos/players/Rascal.jpg", position: "TOP", nameKr: "김광희"  }, { name: "Clid", image: "/photos/players/clid.jpg" , position: "JUG", nameKr: "김태민" }, { name: "Bdd", image: "/photos/players/bdd.jpg", position: "MID", nameKr: "곽보성"  }, { name: "Ruler", image: "/photos/players/Ruler.jpg", position: "BOT", nameKr: "박재혁"  },{ name: "Life", image: "/photos/players/Life.jpg", position: "SUP", nameKr: "김정민"  }] },
            { name: "T1", logo: "/photos/assets/T1.svg", players: [{  name: "Cannna", image: "/photos/players/canna.jpg", position: "TOP", nameKr: "김창동"  }, { name: "Cuzz", image: "/photos/players/Cuzz.jpg" , position: "JUG", nameKr: "문우찬" }, { name: "Faker", image: "/photos/players/Faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Teddy", image: "/photos/players/Teddy.jpg", position: "BOT", nameKr: "박진성"  },{ name: "Effort", image: "/photos/players/Effort.jpg", position: "SUP", nameKr: "이상호"  }] },
            { name: "DRX", logo: "/photos/assets/DRX.svg", players: [{  name: "Doran", image: "/photos/players/Doran.jpg", position: "TOP", nameKr: "최현준"  }, { name: "Pyosik", image: "/photos/players/Pyosik.jpg" , position: "JUG", nameKr: "홍창현" }, { name: "Chovy", image: "/photos/players/chovy.jpg", position: "MID", nameKr: "정지훈"  }, { name: "Deft", image: "/photos/players/Deft.jpg", position: "BOT", nameKr: "김혁규"  },{ name: "Keria", image: "/photos/players/Keria.jpg", position: "SUP", nameKr: "류민석"  }] },
            { name: "KT", logo: "/photos/assets/2021 KT.svg", players: [{  name: "SoHwan", image: "/photos/players/sohwan.jpg", position: "TOP", nameKr: "김준영"  }, { name: "BonO", image: "/photos/players/bono.jpg" , position: "JUG", nameKr: "김기범" }, { name: "Kuro", image: "/photos/players/kuro.jpg", position: "MID", nameKr: "이서행"  }, { name: "Aiming", image: "/photos/players/Aiming.jpg", position: "BOT", nameKr: "김하람"  },{ name: "Tusin", image: "/photos/players/tusin.jpg", position: "SUP", nameKr: "박종익"  }] },
            { name: "DWG", logo: "/photos/assets/DWG.jpg", players: [{  name: "Nuguri", image: "/photos/players/nuguri.jpg", position: "TOP", nameKr: "장하권"  }, { name: "Canyon", image: "/photos/players/Canyon.jpg" , position: "JUG", nameKr: "김건부" }, { name: "ShowMaker", image: "/photos/players/ShowMaker.jpg", position: "MID", nameKr: "허수"  }, { name: "Nuclear", image: "/photos/players/nuclear.jpg", position: "BOT", nameKr: "신정현"  },{ name: "BeryL", image: "/photos/players/BeryL.jpg", position: "SUP", nameKr: "조건희"  }] },
            { name: "AF", logo: "/photos/assets/2020 AF.jpg", players: [{  name: "Kiin", image: "/photos/players/Kiin.jpg", position: "TOP", nameKr: "김기인"  }, { name: "Spirit", image: "/photos/players/spirit.jpg" , position: "JUG", nameKr: "이다윤" }, { name: "Fly", image: "/photos/players/fly.jpg", position: "MID", nameKr: "송용준"  }, { name: "Mystic", image: "/photos/players/mystic.jpg", position: "BOT", nameKr: "진성준"  },{ name: "Jelly", image: "/photos/players/jelly.jpg", position: "SUP", nameKr: "손호경"  }] },
            { name: "APK", logo: "/photos/assets/APK.jpg", players: [{  name: "Ikssu", image: "/photos/players/ikssu.jpg", position: "TOP", nameKr: "전익수"  }, { name: "Flawless", image: "/photos/players/flawless.jpg" , position: "JUG", nameKr: "성영준" }, { name: "Cover", image: "/photos/players/cover.jpg", position: "MID", nameKr: "김주언"  }, { name: "HybriD", image: "/photos/players/hybrid.jpg", position: "BOT", nameKr: "이우진"  },{ name: "Secret", image: "/photos/players/secret.jpg", position: "SUP", nameKr: "박기선"  }] },
            { name: "HLE", logo: "/photos/assets/HLE.svg", players: [{  name: "Cuvee", image: "/photos/players/cuvee.jpg", position: "TOP", nameKr: "이성진"  }, { name: "Haru", image: "/photos/players/haru.jpg" , position: "JUG", nameKr: "강민승" }, { name: "Tempt", image: "/photos/players/tempt.jpg", position: "MID", nameKr: "강명구"  }, { name: "Vsta", image: "/photos/players/Vsta.jpg", position: "BOT", nameKr: "오효성"  },{ name: "Lehends", image: "/photos/players/Lehends.jpg", position: "SUP", nameKr: "손시우"  }] },
            { name: "SB", logo: "/photos/assets/2020 SB.jpg", players: [{  name: "Summit", image: "/photos/players/summit.jpg", position: "TOP", nameKr: "박우태"  }, { name: "Onfleek", image: "/photos/players/onfleek.jpg" , position: "JUG", nameKr: "김장겸" }, { name: "Dove", image: "/photos/players/dove.jpg", position: "MID", nameKr: "김재연"  }, { name: "Route", image: "/photos/players/route.jpg", position: "BOT", nameKr: "문검수"  },{ name: "GorlliA", image: "/photos/players/gorllia.jpg", position: "SUP", nameKr: "강범현"  }] },
            { name: "GRF", logo: "/photos/assets/GRIFFIN.jpg", players: [{  name: "Sword", image: "/photos/players/sword.jpg", position: "TOP", nameKr: "최성원"  }, { name: "Tarzan", image: "/photos/players/tarzan.jpg" , position: "JUG", nameKr: "이승용" }, { name: "Ucal", image: "/photos/players/Ucal.jpg", position: "MID", nameKr: "손우현"  }, { name: "Viper", image: "/photos/players/Viper.jpg", position: "BOT", nameKr: "박도현"  },{ name: "Irove", image: "/photos/players/irove.jpg", position: "SUP", nameKr: "정상현"  }] },
        ],
        2019: [
            { name: "GRF", logo: "/photos/assets/GRIFFIN.jpg", players: [{  name: "Sword", image: "/photos/players/Sword.jpg", position: "TOP", nameKr: "최성원"  }, { name: "Tarzan", image: "/photos/players/tarzan.jpg" , position: "JUG", nameKr: "이승용" }, { name: "Chovy", image: "/photos/players/chovy.jpg", position: "MID", nameKr: "정지훈"  }, { name: "Viper", image: "/photos/players/viper.jpg", position: "BOT", nameKr: "박도현"  },{ name: "Lehends", image: "/photos/players/Lehends.jpg", position: "SUP", nameKr: "손시우"  }] },
            { name: "SKT", logo: "/photos/assets/SKT.svg", players: [{  name: "Khan", image: "/photos/players/khan.jpg", position: "TOP", nameKr: "김동하"  }, { name: "Clid", image: "/photos/players/Clid.jpg" , position: "JUG", nameKr: "김태민" }, { name: "Faker", image: "/photos/players/Faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Teddy", image: "/photos/players/Teddy.jpg", position: "BOT", nameKr: "박진성"  },{ name: "Mata", image: "/photos/players/Mata.jpg", position: "SUP", nameKr: "조세형"  }] },
            { name: "KZ", logo: "/photos/assets/KZ.jpg", players: [{  name: "Rascal", image: "/photos/players/rascal.jpg", position: "TOP", nameKr: "김광희"  }, { name: "Cuzz", image: "/photos/players/cuzz.jpg" , position: "JUG", nameKr: "문우찬" }, { name: "PawN", image: "/photos/players/Pawn.jpg", position: "MID", nameKr: "허원석"  }, { name: "Deft", image: "/photos/players/Deft.jpg", position: "BOT", nameKr: "김혁규"  },{ name: "TusiN", image: "/photos/players/tusin.jpg", position: "SUP", nameKr: "박종익"  }] },
            { name: "SB", logo: "/photos/assets/2020 SB.jpg", players: [{  name: "Summit", image: "/photos/players/summit.jpg", position: "TOP", nameKr: "박우태"  }, { name: "OnFleek", image: "/photos/players/onfleek.jpg" , position: "JUG", nameKr: "김장겸" }, { name: "Dove", image: "/photos/players/dove.jpg", position: "MID", nameKr: "김재연"  }, { name: "Ghost", image: "/photos/players/ghost.jpg", position: "BOT", nameKr: "장용준"  },{ name: "Joker", image: "/photos/players/joker.jpg", position: "SUP", nameKr: "조재읍"  }] },
            { name: "DWG", logo: "/photos/assets/DWG.jpg", players: [{  name: "Nuguri", image: "/photos/players/nuguri.jpg", position: "TOP", nameKr: "장하권"  }, { name: "Canyon", image: "/photos/players/Canyon.jpg" , position: "JUG", nameKr: "김건부" }, { name: "ShowMaker", image: "/photos/players/ShowMaker.jpg", position: "MID", nameKr: "허수"  }, { name: "Nuclear", image: "/photos/players/nuclear.jpg", position: "BOT", nameKr: "신정현"  },{ name: "Hoit", image: "/photos/players/Hoit.jpg", position: "SUP", nameKr: "류호성"  }] },
            { name: "HLE", logo: "/photos/assets/hle.svg", players: [{  name: "Thal", image: "/photos/players/thal.jpg", position: "TOP", nameKr: "박권혁"  }, { name: "bonO", image: "/photos/players/bono.jpg" , position: "JUG", nameKr: "김기범" }, { name: "Tempt", image: "/photos/players/tempt.jpg", position: "MID", nameKr: "강명구"  }, { name: "Sangyoon", image: "/photos/players/sangyoon.jpg", position: "BOT", nameKr: "권상윤"  },{ name: "Key", image: "/photos/players/key.jpg", position: "SUP", nameKr: "김한기"  }] },
            { name: "GEN.G", logo: "/photos/assets/GEN.G.SVG", players: [{  name: "CuVee", image: "/photos/players/cuvee.jpg", position: "TOP", nameKr: "이성진"  }, { name: "Peanut", image: "/photos/players/peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Fly", image: "/photos/players/fly.jpg", position: "MID", nameKr: "송용준"  }, { name: "Ruler", image: "/photos/players/ruler.jpg", position: "BOT", nameKr: "박재혁"  },{ name: "Life", image: "/photos/players/life.jpg", position: "SUP", nameKr: "김정민"  }] },
            { name: "AF", logo: "/photos/assets/2020 AF.jpg", players: [{  name: "Kiin", image: "/photos/players/kiin.jpg", position: "TOP", nameKr: "김기인"  }, { name: "Dread", image: "/photos/players/dread.jpg" , position: "JUG", nameKr: "이진혁" }, { name: "Ucal", image: "/photos/players/ucal.jpg", position: "MID", nameKr: "손우현"  }, { name: "Aiming", image: "/photos/players/aiming.jpg", position: "BOT", nameKr: "김하람"  },{ name: "Jelly", image: "/photos/players/jelly.jpg", position: "SUP", nameKr: "손호경"  }] },
            { name: "KT", logo: "/photos/assets/2021 KT.SVG", players: [{  name: "Smeb", image: "/photos/players/smeb.jpg", position: "TOP", nameKr: "손경호"  }, { name: "Score", image: "/photos/players/score.jpg" , position: "JUG", nameKr: "고동빈" }, { name: "Bdd", image: "/photos/players/bdd.jpg", position: "MID", nameKr: "곽보성"  }, { name: "Zenit", image: "/photos/players/zenit.jpg", position: "BOT", nameKr: "전태권"  },{ name: "SnowFlower", image: "/photos/players/snowflower.jpg", position: "SUP", nameKr: "노회종"  }] },
            { name: "JAG", logo: "/photos/assets/JIN AIR.SVG", players: [{  name: "Lindarang", image: "/photos/players/lindarang.jpg", position: "TOP", nameKr: "허만흥"  }, { name: "Malrang", image: "/photos/players/malrang.jpg" , position: "JUG", nameKr: "김근성" }, { name: "Grace", image: "/photos/players/grace.jpg", position: "MID", nameKr: "이찬주"  }, { name: "Stitch", image: "/photos/players/stitch.jpg", position: "BOT", nameKr: "이승주"  },{ name: "Nova", image: "/photos/players/nova.jpg", position: "SUP", nameKr: "박찬호"  }] },
        ],
        2018: [
            { name: "KZ", logo: "/photos/assets/KZ.jpg", players: [{  name: "Khan", image: "/photos/players/khan.jpg", position: "TOP", nameKr: "김동하"  }, { name: "Peanut", image: "/photos/players/peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Bdd", image: "/photos/players/bdd.jpg", position: "MID", nameKr: "곽보성"  }, { name: "Pray", image: "/photos/players/pray.jpg", position: "BOT", nameKr: "김종인"  },{ name: "Gorilla", image: "/photos/players/gorilla.jpg", position: "SUP", nameKr: "강범현"  }] },
            { name: "AF", logo: "/photos/assets/2020 AF.jpg", players: [{  name: "Kiin", image: "/photos/players/kiin.jpg", position: "TOP", nameKr: "김기인"  }, { name: "Spirit", image: "/photos/players/spirit.jpg" , position: "JUG", nameKr: "이다윤" }, { name: "Kuro", image: "/photos/players/kuro.jpg", position: "MID", nameKr: "이서행"  }, { name: "Kramer", image: "/photos/players/kramer.jpg", position: "BOT", nameKr: "하종훈"  },{ name: "Tusin", image: "/photos/players/tusin.jpg", position: "SUP", nameKr: "박종익"  }] },
            { name: "KT", logo: "/photos/assets/2021 KT.svg", players: [{  name: "Smeb", image: "/photos/players/smeb.jpg", position: "TOP", nameKr: "송경호"  }, { name: "Score", image: "/photos/players/score.jpg" , position: "JUG", nameKr: "고동빈" }, { name: "Ucal", image: "/photos/players/ucal.jpg", position: "MID", nameKr: "손우현"  }, { name: "Deft", image: "/photos/players/Deft.jpg", position: "BOT", nameKr: "김혁규"  },{ name: "Mata", image: "/photos/players/mata.jpg", position: "SUP", nameKr: "조세형"  }] },
            { name: "SKT", logo: "/photos/assets/SKT.svg", players: [{  name: "Thal", image: "/photos/players/thal.jpg", position: "TOP", nameKr: "박권혁"  }, { name: "Blank", image: "/photos/players/blank.jpg" , position: "JUG", nameKr: "강선구" }, { name: "Faker", image: "/photos/players/faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Bang", image: "/photos/players/bang.jpg", position: "BOT", nameKr: "배준식"  },{ name: "Wolf", image: "/photos/players/wolf.jpg", position: "SUP", nameKr: "이재완"  }] },
            { name: "KSV", logo: "/photos/assets/KSV.jpg", players: [{  name: "CuVee", image: "/photos/players/cuvee.jpg", position: "TOP", nameKr: "이성진"  }, { name: "Ambition", image: "/photos/players/ambition.jpg" , position: "JUG", nameKr: "강찬용" }, { name: "Crown", image: "/photos/players/crown.jpg", position: "MID", nameKr: "이민호"  }, { name: "Ruler", image: "/photos/players/ruler.jpg", position: "BOT", nameKr: "박재혁"  },{ name: "CoreJJ", image: "/photos/players/corejj.jpg", position: "SUP", nameKr: "조용인"  }] },
            { name: "ROX", logo: "/photos/assets/rox.jpg", players: [{  name: "Lindarang", image: "/photos/players/lindarang.jpg", position: "TOP", nameKr: "허만흥"  }, { name: "Seonghwan", image: "/photos/players/Seonghwan.jpg" , position: "JUG", nameKr: "윤성환" }, { name: "Lava", image: "/photos/players/lava.jpg", position: "MID", nameKr: "김태훈"  }, { name: "sangyoon", image: "/photos/players/sangyoon.jpg", position: "BOT", nameKr: "권상윤"  },{ name: "Key", image: "/photos/players/key.jpg", position: "SUP", nameKr: "김한기"  }] },
            { name: "JAG", logo: "/photos/assets/jin air.svg", players: [{  name: "SoHwan", image: "/photos/players/soHwan.jpg", position: "TOP", nameKr: "김준영"  }, { name: "UmTi", image: "/photos/players/umti.jpg" , position: "JUG", nameKr: "엄성현" }, { name: "Grace", image: "/photos/players/grace.jpg", position: "MID", nameKr: "이찬주"  }, { name: "Teddy", image: "/photos/players/teddy.jpg", position: "BOT", nameKr: "박진성"  },{ name: "Wraith", image: "/photos/players/wraith.jpg", position: "SUP", nameKr: "권지민"  }] },
            { name: "BBQ", logo: "/photos/assets/bbq.jpg", players: [{  name: "Crazy", image: "/photos/players/crazy.jpg", position: "TOP", nameKr: "김재희"  }, { name: "Trick", image: "/photos/players/trick.jpg" , position: "JUG", nameKr: "김강윤" }, { name: "Tempt", image: "/photos/players/tempt.jpg", position: "MID", nameKr: "강명구"  }, { name: "Ghost", image: "/photos/players/ghost.jpg", position: "BOT", nameKr: "장용준"  },{ name: "IgNar", image: "/photos/players/ignar.jpg", position: "SUP", nameKr: "이동근"  }] },
            { name: "MVP", logo: "/photos/assets/mvp.svg", players: [{  name: "ADD", image: "/photos/players/add.jpg", position: "TOP", nameKr: "강건모"  }, { name: "Beyond", image: "/photos/players/beyond.jpg" , position: "JUG", nameKr: "김규석" }, { name: "LAN", image: "/photos/players/lan.jpg", position: "MID", nameKr: "안준형"  }, { name: "Pilot", image: "/photos/players/pilot.jpg", position: "BOT", nameKr: "나우형"  },{ name: "Max", image: "/photos/players/max.jpg", position: "SUP", nameKr: "정종빈"  }] },
            { name: "KDM", logo: "/photos/assets/kdm.jpg", players: [{  name: "Roach", image: "/photos/players/roach.jpg", position: "TOP", nameKr: "김강희"  }, { name: "Raise", image: "/photos/players/raise.jpg" , position: "JUG", nameKr: "오지환" }, { name: "Edge", image: "/photos/players/edge.jpg", position: "MID", nameKr: "이호성"  }, { name: "SSol", image: "/photos/players/ssol.jpg", position: "BOT", nameKr: "서진솔"  },{ name: "Secret", image: "/photos/players/secret.jpg", position: "SUP", nameKr: "박기선"  }] },
        ],
        2017: [
            { name: "ROX", logo: "/photos/assets/skt.svg", players: [{  name: "Huni", image: "/photos/players/huni.jpg", position: "TOP", nameKr: "허승훈"  }, { name: "Peanut", image: "/photos/players/peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Faker", image: "/photos/players/faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Bang", image: "/photos/players/bang.jpg", position: "BOT", nameKr: "배준식"  },{ name: "Wolf", image: "/photos/players/wolf.jpg", position: "SUP", nameKr: "이재완"  }] },
            { name: "SSG", logo: "/photos/assets/SSG.jpg", players: [{  name: "CuVee", image: "/photos/players/cuvee.jpg", position: "TOP", nameKr: "이성진"  }, { name: "Haru", image: "/photos/players/haru.jpg" , position: "JUG", nameKr: "강민승" }, { name: "Crown", image: "/photos/players/crown.jpg", position: "MID", nameKr: "이민호"  }, { name: "Ruler", image: "/photos/players/ruler.jpg", position: "BOT", nameKr: "박재혁"  },{ name: "CoreJJ", image: "/photos/players/corejj.jpg", position: "SUP", nameKr: "조용인"  }] },
            { name: "KT", logo: "/photos/assets/2021 KT.svg", players: [{  name: "Smeb", image: "/photos/players/smeb.jpg", position: "TOP", nameKr: "송경호"  }, { name: "Score", image: "/photos/players/score.jpg" , position: "JUG", nameKr: "고동빈" }, { name: "Pawn", image: "/photos/players/pawn.jpg", position: "MID", nameKr: "허원석"  }, { name: "Deft", image: "/photos/players/Deft.jpg", position: "BOT", nameKr: "김혁규"  },{ name: "Mata", image: "/photos/players/mata.jpg", position: "SUP", nameKr: "조세형"  }] },
            { name: "AF", logo: "/photos/assets/2020 AF.jpg", players: [{  name: "Marin", image: "/photos/players/marin.jpg", position: "TOP", nameKr: "장경환"  }, { name: "Spirit", image: "/photos/players/spirit.jpg" , position: "JUG", nameKr: "이다윤" }, { name: "Kuro", image: "/photos/players/kuro.jpg", position: "MID", nameKr: "이서행"  }, { name: "kramer", image: "/photos/players/kramer.jpg", position: "BOT", nameKr: "하종훈"  },{ name: "Tusin", image: "/photos/players/tusin.jpg", position: "SUP", nameKr: "박종익"  }] },
            { name: "MVP", logo: "/photos/assets/MVP.svg", players: [{  name: "ADD", image: "/photos/players/add.jpg", position: "TOP", nameKr: "강건모"  }, { name: "Beyond", image: "/photos/players/beyond.jpg" , position: "JUG", nameKr: "김규석" }, { name: "lan", image: "/photos/players/lan.jpg", position: "MID", nameKr: "안준형"  }, { name: "MaHa", image: "/photos/players/maha.jpg", position: "BOT", nameKr: "오현식"  },{ name: "Max", image: "/photos/images/max.jpg", position: "SUP", nameKr: "정종빈"  }] },
            { name: "ROX", logo: "/photos/assets/rox.jpg", players: [{  name: "Shy", image: "/photos/players/shy.jpg", position: "TOP", nameKr: "박상면"  }, { name: "Seonghwan", image: "/photos/players/seonghwan.jpg" , position: "JUG", nameKr: "윤성환" }, { name: "Mickey", image: "/photos/players/mickey.jpg", position: "MID", nameKr: "손영민"  }, { name: "Sangyoon", image: "/photos/players/sangyoon.jpg", position: "BOT", nameKr: "권상윤"  },{ name: "Key", image: "/photos/players/key.jpg", position: "SUP", nameKr: "김한기"  }] },
            { name: "LZ", logo: "/photos/assets/LZ.jpg", players: [{  name: "Expession", image: "/photos/players/expession.jpg", position: "TOP", nameKr: "구본택"  }, { name: "Crash", image: "/photos/players/crash.jpg" , position: "JUG", nameKr: "이동우" }, { name: "Fly", image: "/photos/players/fly.jpg", position: "MID", nameKr: "송용준"  }, { name: "Pray", image: "/photos/players/pray.jpg", position: "BOT", nameKr: "김종인"  },{ name: "Gorilla", image: "/photos/players/gorilla.jpg", position: "SUP", nameKr: "강범현"  }] },
            { name: "BBQ", logo: "/photos/assets/BBQ.jpg", players: [{  name: "Crazy", image: "/photos/players/crazy.jpg", position: "TOP", nameKr: "김재희"  }, { name: "Bless", image: "/photos/players/bless.jpg" , position: "JUG", nameKr: "최현웅" }, { name: "Tempt", image: "/photos/players/tempt.jpg", position: "MID", nameKr: "강명구"  }, { name: "Ghost", image: "/photos/players/ghost.jpg", position: "BOT", nameKr: "장용준"  },{ name: "Totoro", image: "/photos/images/totoro.jpg", position: "SUP", nameKr: "은종섭"  }] },
            { name: "JAG", logo: "/photos/assets/jin air.svg", players: [{  name: "Ikssu", image: "/photos/players/ikssu.jpg", position: "TOP", nameKr: "전익수"  }, { name: "Umti", image: "/photos/players/umti.jpg" , position: "JUG", nameKr: "엄성현" }, { name: "Kuzan", image: "/photos/players/kuzan.jpg", position: "MID", nameKr: "이성혁"  }, { name: "Teddy", image: "/photos/players/teddy.jpg", position: "BOT", nameKr: "박진성"  },{ name: "SnowFlower", image: "/photos/players/snowflower.jpg", position: "SUP", nameKr: "노희종"  }] },
            { name: "KDM", logo: "/photos/assets/kdm.jpg", players: [{  name: "Roach", image: "/photos/players/roach.jpg", position: "TOP", nameKr: "김강희"  }, { name: "Punch", image: "/photos/players/punch.jpg" , position: "JUG", nameKr: "손민혁" }, { name: "Edge", image: "/photos/players/edge.jpg", position: "MID", nameKr: "이호성"  }, { name: "SSol", image: "/photos/players/ssol.jpg", position: "BOT", nameKr: "서진솔"  },{ name: "Guger", image: "/photos/players/guger.jpg", position: "SUP", nameKr: "김도엽"  }] },
        ],
        2016: [
            { name: "ROX", logo: "/photos/assets/rox tigers.jpg", players: [{  name: "Smeb", image: "/photos/players/smeb.jpg", position: "TOP", nameKr: "송경호"  }, { name: "Peanut", image: "/photos/players/peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Kuro", image: "/photos/players/kuro.jpg", position: "MID", nameKr: "이서행"  }, { name: "Pray", image: "/photos/images/pray.jpg", position: "BOT", nameKr: "김종인"  },{ name: "Gorilla", image: "/photos/players/gorilla.jpg", position: "SUP", nameKr: "강범현"  }] },
            { name: "KT", logo: "/photos/assets/2021 KT.svg", players: [{  name: "Ssumday", image: "/photos/players/Ssumday.jpg", position: "TOP", nameKr: "김찬호"  }, { name: "Score", image: "/photos/players/score.jpg" , position: "JUG", nameKr: "고동빈" }, { name: "Fly", image: "/photos/players/Fly.jpg", position: "MID", nameKr: "송용준"  }, { name: "Arrow", image: "/photos/images/arrow.jpg", position: "BOT", nameKr: "노동현"  },{ name: "Hachani", image: "/photos/players/hachani.jpg", position: "SUP", nameKr: "하승찬"  }] },
            { name: "SKT", logo: "/photos/assets/skt.svg", players: [{  name: "Duke", image: "/photos/players/duke.jpg", position: "TOP", nameKr: "이호성"  }, { name: "Blank", image: "/photos/players/blank.jpg" , position: "JUG", nameKr: "강선구" }, { name: "Faker", image: "/photos/players/faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Bang", image: "/photos/images/bang.jpg", position: "BOT", nameKr: "배준식"  },{ name: "Wolf", image: "/photos/players/wolf.jpg", position: "SUP", nameKr: "이재완"  }] },
            { name: "JAG", logo: "/photos/assets/jin air.svg", players: [{  name: "Trace", image: "/photos/players/trace.jpg", position: "TOP", nameKr: "여창동"  }, { name: "Winged", image: "/photos/players/winged.jpg" , position: "JUG", nameKr: "박태진" }, { name: "Kuzan", image: "/photos/players/kuzan.jpg", position: "MID", nameKr: "이성혁"  }, { name: "Pilot", image: "/photos/images/pilot.jpg", position: "BOT", nameKr: "나우형"  },{ name: "Chei", image: "/photos/players/chei.jpg", position: "SUP", nameKr: "최선호"  }] },
            { name: "AF", logo: "/photos/assets/2020 AF.jpg", players: [{  name: "Ikssu", image: "/photos/players/ikssu.jpg", position: "TOP", nameKr: "전익수"  }, { name: "Lira", image: "/photos/players/lira.jpg" , position: "JUG", nameKr: "남태유" }, { name: "Mickey", image: "/photos/players/mickey.jpg", position: "MID", nameKr: "손영민"  }, { name: "Sangyoon", image: "/photos/players/sangyoon.jpg", position: "BOT", nameKr: "권상윤"  },{ name: "SnowFlower", image: "/photos/players/snowflower.jpg", position: "SUP", nameKr: "노회종"  }] },
            { name: "SSG", logo: "/photos/assets/SSG.jpg", players: [{  name: "CuVee", image: "/photos/players/cuvee.jpg", position: "TOP", nameKr: "이성진"  }, { name: "Ambition", image: "/photos/players/ambition.jpg" , position: "JUG", nameKr: "강찬용" }, { name: "Crown", image: "/photos/players/crown.jpg", position: "MID", nameKr: "이민호"  }, { name: "CoreJJ", image: "/photos/players/corejj.jpg", position: "BOT", nameKr: "조용인"  },{ name: "Wraith", image: "/photos/players/wraith.jpg", position: "SUP", nameKr: "권지민"  }] },
            { name: "LZ", logo: "/photos/assets/LZ.jpg", players: [{  name: "Expession", image: "/photos/players/expession.jpg", position: "TOP", nameKr: "구본택"  }, { name: "Chaser", image: "/photos/players/chaser.jpg" , position: "JUG", nameKr: "이상현" }, { name: "Coco", image: "/photos/players/coco.jpg", position: "MID", nameKr: "신진영"  }, { name: "Cpt Jack", image: "/photos/players/cpt jack.jpg", position: "BOT", nameKr: "강형우"  },{ name: "Pure", image: "/photos/players/pure.jpg", position: "SUP", nameKr: "김진선"  }] },
            { name: "CJ", logo: "/photos/assets/CJ.svg", players: [{  name: "Untara", image: "/photos/players/untara.jpg", position: "TOP", nameKr: "박의진"  }, { name: "Bubbling", image: "/photos/players/bubbling.jpg" , position: "JUG", nameKr: "박준형" }, { name: "Sky", image: "/photos/players/sky.jpg", position: "MID", nameKr: "김하늘"  }, { name: "Kramer", image: "/photos/players/kramer.jpg", position: "BOT", nameKr: "하종훈"  },{ name: "MadLife", image: "/photos/players/madlife.jpg", position: "SUP", nameKr: "홍민기"  }] },
            { name: "SSB", logo: "/photos/assets/ssb.jpg", players: [{  name: "Soul", image: "/photos/players/Soul.jpg", position: "TOP", nameKr: "서현석"  }, { name: "Flawless", image: "/photos/players/flawless.jpg" , position: "JUG", nameKr: "성연준" }, { name: "Sasin", image: "/photos/players/sasin.jpg", position: "MID", nameKr: "오승주"  }, { name: "Nuclear", image: "/photos/players/nuclear.jpg", position: "BOT", nameKr: "신정현"  },{ name: "Secret", image: "/photos/players/secret.jpg", position: "SUP", nameKr: "김건우"  }] },
            { name: "KDM", logo: "/photos/assets/2016 kdm.jpg", players: [{  name: "Hipo", image: "/photos/players/hipo.jpg", position: "TOP", nameKr: "석현준"  }, { name: "Crush", image: "/photos/players/crush.jpg" , position: "JUG", nameKr: "김준서" }, { name: "Edge", image: "/photos/players/edge.jpg", position: "MID", nameKr: "이호성"  }, { name: "Ssol", image: "/photos/players/ssol.jpg", position: "BOT", nameKr: "서진솔"  },{ name: "Guger", image: "/photos/players/guger.jpg", position: "SUP", nameKr: "김도엽"  }] },
        ],
        2015: [
            { name: "GET", logo: "/photos/assets/Get.jpg", players: [{  name: "Smeb", image: "/photos/players/smeb.jpg", position: "TOP", nameKr: "송경호"  }, { name: "Lee", image: "/photos/players/lee.jpg" , position: "JUG", nameKr: "이호진" }, { name: "Kuro", image: "/photos/players/kuro.jpg", position: "MID", nameKr: "이서행"  }, { name: "Pray", image: "/photos/players/pray.jpg", position: "BOT", nameKr: "김종인"  },{ name: "Gorilla", image: "/photos/players/gorilla.jpg", position: "SUP", nameKr: "강범현"  }] },
            { name: "SKT", logo: "/photos/assets/skt.svg", players: [{  name: "Marin", image: "/photos/players/marin.jpg", position: "TOP", nameKr: "장경환"  }, { name: "Bengi", image: "/photos/players/bengi.jpg" , position: "JUG", nameKr: "배성웅" }, { name: "Faker", image: "/photos/players/Faker.jpg", position: "MID", nameKr: "이상혁"  }, { name: "Bang", image: "/photos/players/bang.jpg", position: "BOT", nameKr: "배준식"  },{ name: "Wolf", image: "/photos/players/wolf.jpg", position: "SUP", nameKr: "이재완"  }] },
            { name: "CJ", logo: "/photos/assets/cj.svg", players: [{  name: "Shy", image: "/photos/players/shy.jpg", position: "TOP", nameKr: "박상면"  }, { name: "Ambition", image: "/photos/players/ambition.jpg" , position: "JUG", nameKr: "강찬용" }, { name: "Coco", image: "/photos/players/coco.jpg", position: "MID", nameKr: "신진영"  }, { name: "Space", image: "/photos/players/space.jpg", position: "BOT", nameKr: "선호산"  },{ name: "MadLife", image: "/photos/players/madlife.jpg", position: "SUP", nameKr: "홍민기"  }] },
            { name: "JAG", logo: "/photos/assets/jin air.svg", players: [{  name: "Trace", image: "/photos/players/trace.jpg", position: "TOP", nameKr: "여창동"  }, { name: "Chaser", image: "/photos/players/chaser.jpg" , position: "JUG", nameKr: "이상현" }, { name: "GBM", image: "/photos/players/gbm.jpg", position: "MID", nameKr: "이창석"  }, { name: "Pilot", image: "/photos/players/pilot.jpg", position: "BOT", nameKr: "나우형"  },{ name: "Chei", image: "/photos/players/chei.jpg", position: "SUP", nameKr: "최선호"  }] },
            { name: "KT", logo: "/photos/assets/2021 kt.svg", players: [{  name: "Ssumday", image: "/photos/players/ssumday.jpg", position: "TOP", nameKr: "김찬호"  }, { name: "Score", image: "/photos/players/score.jpg" , position: "JUG", nameKr: "고동빈" }, { name: "Nagne", image: "/photos/players/nagne.jpg", position: "MID", nameKr: "김상문"  }, { name: "Arrow", image: "/photos/players/arrow.jpg", position: "BOT", nameKr: "노동현"  },{ name: "Hachani", image: "/photos/players/hachani.jpg", position: "SUP", nameKr: "하승찬"  }] },
            { name: "NJF", logo: "/photos/assets/njf.jpg", players: [{  name: "Duke", image: "/photos/players/duke.jpg", position: "TOP", nameKr: "이호성"  }, { name: "peanut", image: "/photos/players/peanut.jpg" , position: "JUG", nameKr: "한왕호" }, { name: "Ggoong", image: "/photos/players/ggoong.jpg", position: "MID", nameKr: "유병준"  }, { name: "Ohq", image: "/photos/players/ohq.jpg", position: "BOT", nameKr: "오규민"  },{ name: "Cain", image: "/photos/players/cain.jpg", position: "SUP", nameKr: "장누리"  }] },
            { name: "IM", logo: "/photos/assets/im.jpg", players: [{  name: "Lil4c", image: "/photos/players/lilac.jpg", position: "TOP", nameKr: "전호진"  }, { name: "Wisdom", image: "/photos/players/wisdom.jpg" , position: "JUG", nameKr: "김태완" }, { name: "Frozen", image: "/photos/players/frozen.jpg", position: "MID", nameKr: "김태일"  }, { name: "SONSTAR", image: "/photos/players/sonstar.jpg", position: "BOT", nameKr: "손승익"  },{ name: "Tusin", image: "/photos/players/tusin.jpg", position: "SUP", nameKr: "박종익"  }] },
            { name: "SSG", logo: "/photos/assets/ssg.jpg", players: [{  name: "Cuvee", image: "/photos/players/cuvee.jpg", position: "TOP", nameKr: "이성진"  }, { name: "Eve", image: "/photos/players/eve.jpg" , position: "JUG", nameKr: "서준철" }, { name: "BlisS", image: "/photos/players/bliss.jpg", position: "MID", nameKr: "박종원"  }, { name: "Fury", image: "/photos/players/fury.jpg", position: "BOT", nameKr: "이진용"  },{ name: "Wraith", image: "/photos/players/wraith.jpg", position: "SUP", nameKr: "권지민"  }] },
        ],
        2014: [
            { name: "SSB", logo: "/photos/assets/ssb.jpg", players: [{ name: "Acorn", image: "/photos/players/acorn.jpg", position: "TOP", nameKr: "최천주" }, { name: "Spirit", image: "/photos/players/spirit.jpg" , position: "JUG", nameKr: "이다윤" }, { name: "Dade", image: "/photos/players/dade.jpg", position: "MID", nameKr: "배어진" }, { name: "Deft", image: "/photos/images/deft.jpg", position: "BOT", nameKr: "김혁규" }, { name: "Heart", image: "/photos/images/heart.jpg", position: "SUP", nameKr: "이관형" }] },
            { name: "NWS", logo: "/photos/assets/nws.jpg", players: [{ name: "Save", image: "/photos/players/save.jpg", position: "TOP", nameKr: "백영진" }, { name: "watch", image: "/photos/players/watch.jpg" , position: "JUG", nameKr: "조재걸" }, { name: "Ggoong", image: "/photos/players/ggoong.jpg", position: "MID", nameKr: "유병준" }, { name: "Zefa", image: "/photos/players/zefa.jpg", position: "BOT", nameKr: "이재민" }, { name: "GorillA", image: "/photos/players/gorllia.jpg", position: "SUP", nameKr: "강범현" }] },
            { name: "SSO", logo: "/photos/assets/sso.jpg", players: [{ name: "Looper", image: "/photos/players/looper.jpg", position: "TOP", nameKr: "장형석" }, { name: "DanDy", image: "/photos/players/dandy.jpg" , position: "JUG", nameKr: "최인규" }, { name: "PawN", image: "/photos/players/pawn.jpg", position: "MID", nameKr: "허원석" }, { name: "imp", image: "/photos/players/imp.jpg", position: "BOT", nameKr: "구승빈" }, { name: "Mata", image: "/photos/players/mata.jpg", position: "SUP", nameKr: "조세형" }] },
            { name: "CJB", logo: "/photos/assets/cjb.jpg", players: [{ name: "Flame", image: "/photos/players/flame.jpg", position: "TOP", nameKr: "이호종" }, { name: "Daydream", image: "/photos/players/daydream.jpg" , position: "JUG", nameKr: "강경민" }, { name: "Ambition", image: "/photos/players/ambition.jpg", position: "MID", nameKr: "강찬용" }, { name: "Emperor", image: "/photos/players/emperor.jpg", position: "BOT", nameKr: "김진현" }, { name: "Lustboy", image: "/photos/players/lustboy.jpg", position: "SUP", nameKr: "함장식" }] },
            { name: "KT.B", logo: "/photos/assets/kt b.jpg", players: [{ name: "Leopard", image: "/photos/players/duke.jpg", position: "TOP", nameKr: "이호성" }, { name: "inSec", image: "/photos/players/insec.jpg" , position: "JUG", nameKr: "최인석" }, { name: "Ryu", image: "/photos/players/ryu.jpg", position: "MID", nameKr: "류상욱" }, { name: "Score", image: "/photos/players/score.jpg", position: "BOT", nameKr: "고동빈" }, { name: "Mafa", image: "/photos/players/mafa.jpg", position: "SUP", nameKr: "원종세" }] },
            { name: "CJ.F", logo: "/photos/assets/cj.f.jpg", players: [{ name: "Shy", image: "/photos/players/shy.jpg", position: "TOP", nameKr: "박상면" }, { name: "Helios", image: "/photos/players/helios.jpg" , position: "JUG", nameKr: "신동진" }, { name: "CoCo", image: "/photos/players/coco.jpg", position: "MID", nameKr: "신진영" }, { name: "Space", image: "/photos/players/space.jpg", position: "BOT", nameKr: "선호산" }, { name: "MadLife", image: "/photos/players/madlife.jpg", position: "SUP", nameKr: "홍민기" }] },
            { name: "KT.A", logo: "/photos/assets/kt a.jpg", players: [{ name: "ssumday", image: "/photos/players/ssumday.jpg", position: "TOP", nameKr: "김찬호" }, { name: "KaKAO", image: "/photos/players/kakao.jpg" , position: "JUG", nameKr: "이병권" }, { name: "RooKie", image: "/photos/players/rookie.jpg", position: "MID", nameKr: "송의진" }, { name: "Arrow", image: "/photos/players/arrow.jpg", position: "BOT", nameKr: "노동현" }, { name: "Hachani", image: "/photos/players/hachani.jpg", position: "SUP", nameKr: "하승찬" }] },
            { name: "SKT K", logo: "/photos/assets/skt k.jpg", players: [{ name: "Impact", image: "/photos/players/impact.jpg", position: "TOP", nameKr: "정언영" }, { name: "Bengi", image: "/photos/players/bengi.jpg" , position: "JUG", nameKr: "배성웅" }, { name: "Faker", image: "/photos/images/Faker.png", position: "MID", nameKr: "이상혁" }, { name: "Piglet", image: "/photos/players/piglet.jpg", position: "BOT", nameKr: "채광진" }, { name: "PoohManDu", image: "/photos/players/poohmandu.jpg", position: "SUP", nameKr: "이정현" }] },
            { name: "NBS", logo: "/photos/assets/nbs.jpg", players: [{ name: "Expession", image: "/photos/players/expession.jpg", position: "TOP", nameKr: "이정현" }, { name: "Watch", image: "/photos/players/watch.jpg" , position: "JUG", nameKr: "조재걸" }, { name: "Nagne", image: "/photos/players/nagne.jpg", position: "MID", nameKr: "김상문" }, { name: "Pray", image: "/photos/players/pray.jpg", position: "BOT", nameKr: "김종인" }, { name: "Cain", image: "/photos/players/cain.jpg", position: "SUP", nameKr: "장누리" }] },
            { name: "SKT S", logo: "/photos/assets/skt s.jpg", players: [{ name: "MaRin", image: "/photos/players/marin.jpg", position: "TOP", nameKr: "장경환" }, { name: "H0R0", image: "/photos/players/h0r0.jpg" , position: "JUG", nameKr: "조재환" }, { name: "Easyhoon", image: "/photos/players/easyhoon.jpg", position: "MID", nameKr: "이지훈" }, { name: "Bang", image: "/photos/players/bang.jpg", position: "BOT", nameKr: "강선구" }, { name: "Wolf", image: "/photos/players/wolf.jpg", position: "SUP", nameKr: "이재완" }] },
            {name: "IM #1", logo: "/photos/assets/im.jpg", players: [{ name: "Smeb", image: "/photos/players/smeb.jpg", position: "TOP", nameKr: "송경호" }, { name: "Lilac", image: "/photos/players/lilac.jpg" , position: "JUG", nameKr: "전호진" }, { name: "MidKing", image: "/photos/players/midking.jpg", position: "MID", nameKr: "박수용" }, { name: "Violet", image: "/photos/players/violet.jpg", position: "BOT", nameKr: "하효석" }, { name: "BBuing", image: "/photos/players/bbuing.jpg", position: "SUP", nameKr: "김현철" }] },
            { name: "IM #2", logo: "/photos/assets/im2.jpg", players: [{ name: "Apple", image: "/photos/players/apple.jpg", position: "TOP", nameKr: "정철우" }, { name: "Reign Over", image: "/photos/players/reignover.jpg" , position: "JUG", nameKr: "김의진" }, { name: "kurO", image: "/photos/players/kuro.jpg", position: "MID", nameKr: "이서행" }, { name: "BetKyo", image: "/photos/players/betkyo.jpg", position: "BOT", nameKr: "이승민" }, { name: "Paragon", image: "/photos/players/paragon.jpg", position: "SUP", nameKr: "박종익" }] },
            { name: "PO", logo: "/photos/assets/po.jpg", players: [{ name: "sTL", image: "/photos/players/stl.jpg", position: "TOP", nameKr: "이성욱" }, { name: "Swing", image: "/photos/players/swing.jpg" , position: "JUG", nameKr: "이수연" }, { name: "DoGGi", image: "/photos/players/doggi.jpg", position: "MID", nameKr: "김한영" }, { name: "DeaL", image: "/photos/players/deal.jpg", position: "BOT", nameKr: "정석진" }, { name: "Lux", image: "/photos/players/lux.jpg", position: "SUP", nameKr: "박진수" }] },
            { name: "FIO", logo: "/photos/assets/fio.jpg", players: [{ name: "Roach", image: "/photos/players/roach.jpg", position: "TOP", nameKr: "김강희" }, { name: "ActScene", image: "/photos/players/chaser.jpg" , position: "JUG", nameKr: "이상현" }, { name: "Raptor", image: "/photos/players/raptor.jpg", position: "MID", nameKr: "전명준" }, { name: "Mystic", image: "/photos/players/mystic.jpg", position: "BOT", nameKr: "진성준" }, { name: "Miko", image: "/photos/players/miko.jpg", position: "SUP", nameKr: "김상원" }] },
            { name: "JAG.F", logo: "/photos/assets/jag.f.jpg", players: [{ name: "Miso", image: "/photos/players/miso.jpg", position: "TOP", nameKr: "서진솔" }, { name: "RealFoxy", image: "/photos/players/realfoxy.jpg" , position: "JUG", nameKr: "윤대영" }, { name: "Ganked By Mom", image: "/photos/players/gankedbymom.jpg", position: "MID", nameKr: "신윤기" }, { name: "BoRoona", image: "/photos/players/boroona.jpg", position: "BOT", nameKr: "이동민" }, { name: "Kish", image: "/photos/players/kish.jpg", position: "SUP", nameKr: "김건우" }] },
            { name: "XS", logo: "/photos/assets/xs.jpg", players: [{ name: "Ren", image: "/photos/players/ren.jpg", position: "TOP", nameKr: "이성재" }, { name: "Vin", image: "/photos/players/vin.jpg" , position: "JUG", nameKr: "노성우" }, { name: "Alvingo", image: "/photos/players/alvingo.jpg", position: "MID", nameKr: "서명완" }, { name: "Ohq", image: "/photos/players/ohq.jpg", position: "BOT", nameKr: "오규민" }, { name: "Ink", image: "/photos/players/ink.jpg", position: "SUP", nameKr: "송영규" }] }
        ],
       2013: [
            { name: "MVP Ozone", logo: "/photos/assets/mvp o.svg", players: [{ name: "Homme", image: "/photos/players/homme.jpg", position: "TOP", nameKr: "윤성영" }, { name: "DanDy", image: "/photos/players/dandy.jpg" , position: "JUG", nameKr: "최인규" }, { name: "Dade", image: "/photos/players/dade.jpg", position: "MID", nameKr: "배어진" }, { name: "imp", image: "/photos/players/imp.jpg", position: "BOT", nameKr: "구승빈" }, { name: "Mata", image: "/photos/players/mata.jpg", position: "SUP", nameKr: "조세형" }] },
            { name: "CJ Entus Blaze", logo: "/photos/assets/cjb.jpg", players: [{ name: "Flame", image: "/photos/players/flame.jpg", position: "TOP", nameKr: "이호종" }, { name: "Helios", image: "/photos/players/helios.jpg" , position: "JUG", nameKr: "신동진" }, { name: "Ambition", image: "/photos/players/ambition.jpg", position: "MID", nameKr: "강찬용" }, { name: "Cpt Jack", image: "/photos/players/cpt jack.jpg", position: "BOT", nameKr: "강형우" }, { name: "Lustboy", image: "/photos/players/lustboy.jpg", position: "SUP", nameKr: "함장식" }] },
            { name: "SKT T1 #2", logo: "/photos/assets/skt k.jpg", players: [{ name: "Impact", image: "/photos/players/impact.jpg", position: "TOP", nameKr: "정언영" }, { name: "Bengi", image: "/photos/players/bengi.jpg" , position: "JUG", nameKr: "배성웅" }, { name: "Faker", image: "/photos/images/Faker.png", position: "MID", nameKr: "이상혁" }, { name: "Piglet", image: "/photos/players/piglet.jpg", position: "BOT", nameKr: "채광진" }, { name: "PoohManDu", image: "/photos/players/poohmandu.jpg", position: "SUP", nameKr: "이정현" }] },
            { name: "KT Rolster B", logo: "/photos/assets/kt b.jpg", players: [{ name: "Ssumday", image: "/photos/players/ssumday.jpg", position: "TOP", nameKr: "김찬호" }, { name: "inSec", image: "/photos/players/insec.jpg" , position: "JUG", nameKr: "최인석" }, { name: "Ryu", image: "/photos/players/ryu.jpg", position: "MID", nameKr: "류상욱" }, { name: "Score", image: "/photos/players/score.jpg", position: "BOT", nameKr: "고동빈" }, { name: "Mafa", image: "/photos/players/mafa.jpg", position: "SUP", nameKr: "원종세" }] },
            { name: "Najin Sword", logo: "/photos/assets/njs.jpg", players: [{ name: "Expession", image: "/photos/players/expession.jpg", position: "TOP", nameKr: "이정현" }, { name: "Watch", image: "/photos/players/watch.jpg" , position: "JUG", nameKr: "조재걸" }, { name: "Ssong", image: "/photos/players/ssong.jpg", position: "MID", nameKr: "이진솔" }, { name: "Pray", image: "/photos/players/pray.jpg", position: "BOT", nameKr: "김종인" }, { name: "GorillA", image: "/photos/players/gorllia.jpg", position: "SUP", nameKr: "강범현" }] },
            { name: "CJ Entus Frost", logo: "/photos/assets/cj.f.jpg", players: [{ name: "Shy", image: "/photos/players/shy.jpg", position: "TOP", nameKr: "박상면" }, { name: "CloudTemplar", image: "/photos/players/cloudtemplar.jpg" , position: "JUG", nameKr: "이현우" }, { name: "Ganked By Mom", image: "/photos/players/gbm.jpg", position: "MID", nameKr: "이창석" }, { name: "Space", image: "/photos/players/space.jpg", position: "BOT", nameKr: "선호산" }, { name: "MadLife", image: "/photos/players/madlife.jpg", position: "SUP", nameKr: "홍민기" }] },
            { name: "KT Rolster A", logo: "/photos/assets/kt a.jpg", players: [{ name: "Leopard", image: "/photos/players/duke.jpg", position: "TOP", nameKr: "이호성" }, { name: "KaKAO", image: "/photos/players/kakao.jpg" , position: "JUG", nameKr: "이병권" }, { name: "RooKie", image: "/photos/players/rookie.jpg", position: "MID", nameKr: "송의진" }, { name: "Arrow", image: "/photos/players/arrow.jpg", position: "BOT", nameKr: "노동현" }, { name: "Hachani", image: "/photos/players/hachani.jpg", position: "SUP", nameKr: "하승찬" }] },
            { name: "Najin White Shield", logo: "/photos/assets/nws.jpg", players: [{ name: "Save", image: "/photos/players/save.jpg", position: "TOP", nameKr: "백영진" }, { name: "NoFe", image: "/photos/players/nofe.jpg" , position: "JUG", nameKr: "정노철" }, { name: "Ggoong", image: "/photos/players/ggoong.jpg", position: "MID", nameKr: "유병준" }, { name: "Zefa", image: "/photos/players/zefa.jpg", position: "BOT", nameKr: "이재민" }, { name: "GorillA", image: "/photos/players/gorllia.jpg", position: "SUP", nameKr: "강범현" }] }
        ],
        2012: [
            { name: "MiG Blaze", logo: "/photos/assets/mig b.jpg", players: [{ name: "Reapered", image: "/photos/players/reapered.jpg", position: "TOP", nameKr: "복한규" }, { name: "Helios", image: "/photos/players/helios.jpg" , position: "JUG", nameKr: "신동진" }, { name: "Ambition", image: "/photos/players/ambition.jpg", position: "MID", nameKr: "강찬용" }, { name: "Cpt Jack", image: "/photos/players/cpt_jack.jpg", position: "BOT", nameKr: "강형우" }, { name: "Lustboy", image: "/photos/players/lustboy.jpg", position: "SUP", nameKr: "함장식" }] },
            { name: "MiG Frost", logo: "/photos/assets/mig f.jpg", players: [{ name: "Shy", image: "/photos/players/shy.jpg", position: "TOP", nameKr: "박상면" }, { name: "CloudTemplar", image: "/photos/players/cloudtemplar.jpg" , position: "JUG", nameKr: "이현우" }, { name: "RapidStar", image: "/photos/players/rapidstar.jpg", position: "MID", nameKr: "정민성" }, { name: "Woong", image: "/photos/players/woong.jpg", position: "BOT", nameKr: "장건웅" }, { name: "MadLife", image: "/photos/players/madlife.jpg", position: "SUP", nameKr: "홍민기" }] },
            { name: "Xenics Storm", logo: "/photos/assets/xs.jpg", players: [{ name: "KimG", image: "/photos/players/kimg.jpg", position: "TOP", nameKr: "김건우" }, { name: "Punch", image: "/photos/players/punch.jpg" , position: "JUG", nameKr: "심성수" }, { name: "Coco", image: "/photos/players/coco.jpg", position: "MID", nameKr: "신진영" }, { name: "Ssol", image: "/photos/players/ssol.jpg", position: "BOT", nameKr: "서진솔" }, { name: "Gunza", image: "/photos/players/gunza.jpg", position: "SUP", nameKr: "정건우" }] },
            { name: "Team OP", logo: "/photos/assets/team op.jpg", players: [{ name: "Suky", image: "/photos/players/suky.jpg", position: "TOP", nameKr: "김대웅" }, { name: "Insec", image: "/photos/players/insec.jpg" , position: "JUG", nameKr: "최인석" }, { name: "MidKing", image: "/photos/players/midking.jpg", position: "MID", nameKr: "박수용" }, { name: "Hiro", image: "/photos/players/hiro.jpg", position: "BOT", nameKr: "정현진" }, { name: "Cheonju", image: "/photos/players/cheonju.jpg", position: "SUP", nameKr: "최천주" }] },
            { name: "NaJin e-mFire", logo: "/photos/assets/nje.jpg", players: [{ name: "Expession", image: "/photos/players/expession.jpg", position: "TOP", nameKr: "이정현" }, { name: "Watch", image: "/photos/players/watch.jpg" , position: "JUG", nameKr: "조재걸" }, { name: "Ssong", image: "/photos/players/ssong.jpg", position: "MID", nameKr: "이진솔" }, { name: "Pray", image: "/photos/players/pray.jpg", position: "BOT", nameKr: "김종인" }, { name: "GorillA", image: "/photos/players/gorllia.jpg", position: "SUP", nameKr: "강범현" }] },
            { name: "Counter Logic Gaming EU", logo: "/photos/assets/clg.jpg", players: [{ name: "Wickd", image: "/photos/players/wickd.jpg", position: "TOP", nameKr: "마틴 샌드크비스트" }, { name: "Snoopeh", image: "/photos/players/snoopeh.jpg" , position: "JUG", nameKr: "스티븐 엘리스" }, { name: "Froggen", image: "/photos/players/froggen.jpg", position: "MID", nameKr: "헨릭 한센" }, { name: "Yellowpete", image: "/photos/players/yellowpete.jpg", position: "BOT", nameKr: "페테르 스콧게르" }, { name: "Krepo", image: "/photos/players/krepo.jpg", position: "SUP", nameKr: "미치 반 페이" }] },
            { name: "MKZ", logo: "/photos/assets/mkz.jpg", players: [{ name: "TOP", image: "/photos/players/top_mkz.jpg", position: "TOP", nameKr: "임찬희" }, { name: "JUG", image: "/photos/players/jug_mkz.jpg" , position: "JUG", nameKr: "이원석" }, { name: "MID", image: "/photos/players/mid_mkz.jpg", position: "MID", nameKr: "이재완" }, { name: "BOT", image: "/photos/players/bot_mkz.jpg", position: "BOT", nameKr: "백종윤" }, { name: "SUP", image: "/photos/players/sup_mkz.jpg", position: "SUP", nameKr: "김범수" }] },
            { name: "Fnatic", logo: "/photos/assets/fnatic.jpg", players: [{ name: "Soaz", image: "/photos/players/soaz.jpg", position: "TOP", nameKr: "폴 부이어" }, { name: "Cyanide", image: "/photos/players/cyanide.jpg" , position: "JUG", nameKr: "라우리 살미넨" }, { name: "xPeke", image: "/photos/players/xpeke.jpg", position: "MID", nameKr: "엔리케 세데뇨" }, { name: "Rekkles", image: "/photos/players/rekkles.jpg", position: "BOT", nameKr: "마르틴 라르손" }, { name: "Nrated", image: "/photos/players/nrated.jpg", position: "SUP", nameKr: "파트릭 파예" }] }
        ]
    };

    function updateTeamAndPlayerInfo(team) {
        teamLogoElement.src = team.logo;
        teamNameElement.textContent = team.name;
        
        playerGrid.innerHTML = '';
        team.players.forEach(player => {
            const playerCard = document.createElement('div');
            playerCard.className = 'player-card';

            playerCard.innerHTML = `
                <div class="player-card-inner">
                    <div class="player-card-face player-card-face--front element">
                        <img src="${player.image}" alt="${player.name}" class="player-image">
                        <div class="player-info">
                            <span class="position">${player.position}</span>
                            <span class="player-name">${player.name}</span>
                            <span class="player-name-kr">${player.nameKr}</span>
                        </div>
                    </div>
                
                    <div class="player-card-face player-card-face--back element">
                        <div class="player-info">
                            <h3 class="player-name">${player.name}</h3>
                            <p>${player.nameKr}</p>
                        </div>
                    </div>
                </div>
            `;

            playerCard.addEventListener('click', () => {
                playerCard.classList.toggle('is-flipped');
            });

            playerGrid.appendChild(playerCard);
        });
        playersSection.style.display = 'block';
    }

    function updateTeamList(year) {
        teamsList.innerHTML = '';
        teams[year].forEach(team => {
            const teamItem = document.createElement('li');
            teamItem.className = 'team-item';
            teamItem.innerHTML = `<img src="${team.logo}" alt="${team.name}" class="team-icon"><span>${team.name}</span>`;
            
            teamItem.addEventListener('click', () => {
                updateTeamAndPlayerInfo(team);
                // Remove active class from all team items
                document.querySelectorAll('.team-item').forEach(item => item.classList.remove('active'));
                // Add active class to the clicked team item
                teamItem.classList.add('active');
            });

            teamsList.appendChild(teamItem);
        });
        // Hide players section when year changes
        playersSection.style.display = 'none';

        if (teams[year].length > 0) {
            const firstTeam = teams[year][0];
            // 첫 번째 team-item 에 .active 추가
            teamsList.querySelector('.team-item').classList.add('active');
            // 첫 번째 팀의 로고/플레이어까지 한 번에 그려 줌
            updateTeamAndPlayerInfo(firstTeam);
        }
    }

    dropdownButton.addEventListener('click', (event) => {
        event.stopPropagation();
        dropdownList.classList.toggle('active');
    });

    dropdownList.querySelectorAll('a').forEach(option => {
        option.addEventListener('click', function(event) {
            event.preventDefault();
            const year = this.getAttribute('data-year');
            teamTitle.firstChild.textContent = `${year} LCK 참가팀`;
            updateTeamList(year);
            dropdownList.classList.remove('active');
        });
    });

    window.addEventListener('click', (event) => {
        if (!dropdownButton.contains(event.target)) {
            dropdownList.classList.remove('active');
        }
    });

    // Initial load
    updateTeamList('2025');
});
